const TRANSLATIONS = {
    en: {
        loading: '{loaded}/{total} loaded',
        click_to_view_quests: '(Click to view quests)',
        xp_format: '{current}/{total} XP',
        rainbow_progress: '{current}/{target} rolls to Rainbow mode',
        rainbow_active: 'Rainbow mode Active!',
        quests_title: 'Quests',
        shop_title: 'Shop',
        inventory_title: 'Inventory',
        tab_skins: 'Skins',
        tab_boosts: 'Boosts',
        empty_skins: 'Oops, looks like there\'s nothing here',
        price: 'Price',
        owned: 'Owned',
        buy: 'Buy',
        equip: 'Equip',
        equipped: 'Equipped',
        duration_sec: '{sec}s',
        duration_min: '{min}m',
        leaderboard_title: 'Leaderboard:',
        filter_lucu: 'By $LUCU',
        filter_min: 'By MIN number',
        you: 'You',
        farm_more: 'Farm more!',
        game_balance: 'Game balance:',
        top_up_stars: 'Top up with Stars',
        top_up_ton: 'Top up with TON',
        topup_enter_amount: 'Enter amount',
        topup_you_give: 'You give:',
        topup_total_amount: 'Total amount:',
        topup_reconnect: 'Reconnect >',
        topup_pay: 'Pay',
        your_wallet: 'Your wallet: ',
        connect_wallet: 'Connect TON wallet',
        disconnect_wallet: 'Disconnect',
        donations_label: 'Donations for the developer:',
        min_number_label: 'Minimum number:',
        invite_block_text: 'Got friends who game? Cash in <span class="leaderboard-badge">10%</span> of their commissions. Let them grind — you shine.',
        invite_btn: 'Invite friends',
        waiting_claim: 'waiting to be claimed',
        your_referrals: 'Your referrals',
        total_credited: 'Total credited',
        give_money: 'Give me money',
        quest_claimed: 'CLAIMED',
        quest_claim: 'CLAIM',
        quest_unavailable: 'Unavailable',
        quest_go: 'GO',
        "Roller Newbie": "Roller Newbie",
        "Dice Flicker": "Dice Flicker",
        "Street Roller": "Street Roller",
        "Lucky Rookie": "Lucky Rookie",
        "Dice Toss Apprentice": "Dice Toss Apprentice",
        "Backalley Gambler": "Backalley Gambler",
        "Risk Taker": "Risk Taker",
        "Combo Beginner": "Combo Beginner",
        "Game Player": "Game Player",
        "Fortune's Favorite": "Fortune's Favorite",
        "High Stakes Novice": "High Stakes Novice",
        "Lucky One": "Lucky One",
        "Dice Flow Master": "Dice Flow Master",
        "Combo Master": "Combo Master",
        "High Roller": "High Roller",
        "Ace in the Hole": "Ace in the Hole",
        "Ace Thrower": "Ace Thrower",
        "Dice Whisperer": "Dice Whisperer",
        "Dice Mage": "Dice Mage",
        "Lord of the Roll": "Lord of the Roll",
        "Casino Phantom": "Casino Phantom",
        "Luck Overlord": "Luck Overlord",
        "Dice Demigod": "Dice Demigod",
        "God of Sixes": "God of Sixes",
        "Rainbow Ruler": "Rainbow Ruler",
        "Eternal Roller": "Eternal Roller",
        "Legend of Luck": "Legend of Luck",
        "Dice Deity": "Dice Deity",
        "Untouchable": "Untouchable",
        "THE GOAT": "THE GOAT",
        "Make {target} Rolls": "Make {target} Rolls",
        "Achieve Rainbow Mode {target} Time": "Achieve Rainbow mode {target} Time",
        "Subscribe to Lucky Cubes!": "Subscribe to Lucky Cubes!",
        "Subscribe to Rayan's Channel!": "Subscribe to Rayan's Channel!",
        "Donate 100 Stars": "Donate 100 Stars",
        "boost_empty": "Haha, activate a boost to be cooler",
        "Extra Cube": "Extra Cube",
        "+2 Cubes": "+2 Cubes",
        "Rainbow Mode": "Rainbow mode",
        "Extra Cube Boost": "Extra Cube Boost",
        "+2 Cubes Boost": "+2 Cubes Boost",
        "Rainbow Mode Boost": "Rainbow Mode Boost",
        "Coin Surge": "Coin Surge",
        "Crit Roll": "Crit Roll",
        "AutoRoll": "AutoRoll",
        "Lucky Streak": "Lucky Streak",
        "Time Freeze": "Time Freeze",
        "HyperTap": "HyperTap",
        'Get an extra cube for 30-100 seconds': 'Get an extra cube for 30-100 seconds',
        'Get +2 cubes for 30-100 seconds': 'Get +2 cubes for 30-100 seconds',
        'Activate Rainbow Mode for 30-100 seconds': 'Activate Rainbow Mode for 30-100 seconds',
        'Multiply coins earned for 2-6 minutes': 'Multiply coins earned for 2-6 minutes',
        'Rare critical rolls give 3-10x XP and coins (2-6 min)': 'Rare critical rolls give 3-10x XP and coins (2-6 min)',
        'Automatic rolls every second for 1-5 minutes': 'Automatic rolls every second for 1-5 minutes',
        'Progressive bonuses for consecutive rolls (3-8 min)': 'Progressive bonuses for consecutive rolls (3-8 min)',
        'Quest timers slow down or stop (2-5 min)': 'Quest timers slow down or stop (2-5 min)',
        'Faster cube response for 5-15 seconds': 'Faster cube response for 5-15 seconds',
        leaderboard_your_rank: "#{rank} {name}",
        change_language: "Change language (RU)",
    },
    ru: {
        loading: '{loaded}/{total} загружено',
        click_to_view_quests: '(Нажми для квестов)',
        xp_format: '{current}/{total} XP',
        rainbow_progress: '{current}/{target} бросков до Радужного сияния',
        rainbow_active: 'Радужное сияние активировано!',
        quests_title: 'Квесты',
        shop_title: 'Магазин',
        inventory_title: 'Инвентарь',
        tab_skins: 'Скины',
        tab_boosts: 'Бусты',
        empty_skins: 'Упс, похоже, здесь ничего нет',
        price: 'Цена',
        owned: 'В наличии',
        buy: 'Купить',
        equip: 'Надеть',
        equipped: 'Надето',
        duration_sec: '{sec}с',
        duration_min: '{min}м',
        leaderboard_title: 'Таблица лидеров:',
        filter_lucu: 'По $LUCU',
        filter_min: 'По МИН числу',
        you: 'Вы',
        farm_more: 'Фарми больше!',
        game_balance: 'Игровой баланс:',
        top_up_stars: 'Пополнить Звездами',
        top_up_ton: 'Пополнить TON',
        topup_enter_amount: 'Введите сумму',
        topup_you_give: 'Вы отдаете:',
        topup_total_amount: 'Итоговая сумма:',
        topup_reconnect: 'Переподключить >',
        topup_pay: 'Оплатить',
        your_wallet: 'Ваш кошелек: ',
        connect_wallet: 'Подключить TON кошелек',
        disconnect_wallet: 'Отключить',
        donations_label: 'Донат разработчику:',
        min_number_label: 'МИН число:',
        invite_block_text: 'Есть друзья-игроки? Забирай <span class="leaderboard-badge">10%</span> от их комиссий. Пусть они фармят — а ты лутай награды.',
        invite_btn: 'Пригласить друзей',
        waiting_claim: 'ждут когда их заберут',
        your_referrals: 'Ваши рефералы',
        total_credited: 'Всего начислено',
        give_money: 'Забрать деньги',
        quest_claimed: 'ПОЛУЧЕНО',
        quest_claim: 'ЗАБРАТЬ',
        quest_unavailable: 'Недоступно',
        quest_go: 'GO',
        "Roller Newbie": "Новичок",
        "Dice Flicker": "Кидала Дайсов",
        "Street Roller": "Уличный Игрок",
        "Lucky Rookie": "Везучий Салага",
        "Dice Toss Apprentice": "Ученик Броска",
        "Backalley Gambler": "Игрок из Подворотни",
        "Risk Taker": "Рисковый Парень",
        "Combo Beginner": "Звезда Комбо",
        "Game Player": "Геймер",
        "Fortune's Favorite": "Любимчик Фортуны",
        "High Stakes Novice": "Новичок Крупных Ставок",
        "Lucky One": "Счастливчик",
        "Dice Flow Master": "Мастер Потока",
        "Combo Master": "Мастер Комбо",
        "High Roller": "Хайроллер",
        "Ace in the Hole": "Туз в Рукаве",
        "Ace Thrower": "Меткий Бросок",
        "Dice Whisperer": "Заклинатель Кубиков",
        "Dice Mage": "Маг Кубиков",
        "Lord of the Roll": "Повелитель Бросков",
        "Casino Phantom": "Фантом Казино",
        "Luck Overlord": "Владыка Удачи",
        "Dice Demigod": "Полубог Дайсов",
        "God of Sixes": "Бог Шестерок",
        "Rainbow Ruler": "Повелитель Радуги",
        "Eternal Roller": "Вечный Игрок",
        "Legend of Luck": "Легенда Удачи",
        "Dice Deity": "Божество Кубиков",
        "Untouchable": "Неприкасаемый",
        "THE GOAT": "THE GOAT",
        "Make {target} Rolls": "Сделать {target} бросков",
        "Achieve Rainbow Mode {target} Time": "Активировать Радужное сияние {target} раз(а)",
        "Subscribe to Lucky Cubes!": "Подписаться на Lucky Cubes!",
        "Subscribe to Rayan's Channel!": "Подписаться на канал Rayan!",
        "Donate 100 Stars": "Задонатить 100 Звезд",
        "boost_empty": "Хаха, активируй буст, чтобы быть круче",
        "Extra Cube": "Доп. Кубик",
        "+2 Cubes": "+2 Кубика",
        "Rainbow Mode": "Радужное сияние",
        "Extra Cube Boost": "Буст: Доп. Кубик",
        "+2 Cubes Boost": "Буст: +2 Кубика",
        "Rainbow Mode Boost": "Буст: Радужное сияние",
        "Coin Surge": "Всплеск Монет",
        "Crit Roll": "Критический Бросок",
        "AutoRoll": "Автобросок",
        "Lucky Streak": "Удачная Полоса",
        "Time Freeze": "Заморозка Времени",
        "HyperTap": "ГиперКлик",
        'Get an extra cube for 30-100 seconds': 'Дополнительный кубик на 30-100 секунд',
        'Get +2 cubes for 30-100 seconds': '+2 кубика на 30-100 секунд',
        'Activate Rainbow Mode for 30-100 seconds': 'Радужное сияние на 30-100 секунд',
        'Multiply coins earned for 2-6 minutes': 'Умножение получаемых монет (2-6 мин)',
        'Rare critical rolls give 3-10x XP and coins (2-6 min)': 'Редкие криты дают х3-х10 XP и монет (2-6 мин)',
        'Automatic rolls every second for 1-5 minutes': 'Автоматические броски каждую секунду (1-5 мин)',
        'Progressive bonuses for consecutive rolls (3-8 min)': 'Прогрессивные бонусы за броски подряд (3-8 мин)',
        'Quest timers slow down or stop (2-5 min)': 'Таймеры квестов замедляются (2-5 мин)',
        'Faster cube response for 5-15 seconds': 'Ускоренный отзыв кубика на 5-15 секунд',
        leaderboard_your_rank: "#{rank} {name}",
        change_language: "Сменить язык (EN)",
    }
};
